language: php
sudo: false
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
matrix:
  fast_finish: true
before_script:
  - composer update --no-interaction
script:
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false